
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`w-full  h-full`}
    >
      <body className="min-h-full flex flex-col w-full overflow-x-hidden">
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
